---
title: "About Us"
---

# What is Airlangga [#OpenScience](https://www.fosteropenscience.eu/content/what-open-science-introduction)?

We are early-career researchers from various scientific backgrounds in Universitas Airlangga, committed to promote and to educate students and young researchers to adopt Open Scientific Practices. We believe that science should be open, reproducible, transparent and accessible to everyone. We believe that the current ways of doing science is too polluted by irresponsible use of crude metrics, unhealthy reward systems, and competition. We want change and improvement by emphasizing the importance of getting (the research) right, not just getting it published! 

Publishing research findings is crucial and should be done accordingly. However, **ensuring and improving research quality** is the most important aspect and should be given top priority and more extensive efforts.

[#OpenScience](https://www.fosteropenscience.eu/content/what-open-science-introduction) is an alternative way of doing science, a social movement, and a norm of scientific progress that potentially could alleviate the [replication crisis](https://en.wikipedia.org/wiki/Replication_crisis). #OpenScience is also a strategy to democratize knowledge thus anyone could actively participate in scientific progress. 

Are you keen on learning more about #OpenScience? [Download our Intro to #OpenScience slides here!](../files/sains-terbuka-intro-template.pdf) Slides are in Bahasa Indonesia and codes are available in our <i class="fab fa-github"></i></a> [repository](https://github.com/sainsterbukaUA/materi-presentasi/blob/master/intro-sainsterbuka-template.Rmd)

We also highly recommend [Open Science Knowledge Base](https://oercommons.org/hubs/OSKB) as your first resort, if you are eager to learn more about #OpenScience.

So if you share similar values, please consider to join our movement!

Please check our [past and planned activities here](https://sainsterbukaua.github.io/en/plannedactivities.html).


# Manifesto

* Encouraging researchers to realise their own biases when conducting research
* Underlining the importance of methodological training, especially for early-career researchers and students
* Promoting interdisciplinary collaboration and team science
* Promoting good research practices
* Encouraging the use of [pre-registration](https://cos.io/prereg/) and [Registered Report](https://cos.io/rr/)
* Underlining the importance of the quality improvement of research reporting (complete & reproducible)
* Encouraging the use of open-source and reproducible software for research (<a href="https://www.r-project.org" target="_blank"><i class="fab fa-r-project"></i></a>, <a href="https://www.python.org/" target="_blank"><i class="fab fa-python"></i></a> and many more)
* Evaluating researchers' performance by looking at their adherence to open and reproducible practices, not just crude metrics (for example, see [Center for Open Science](https://cos.io/about/mission/)'s [Transparency and Openness Promotion Guideline (TOP)](https://cos.io/top/))
* Limiting the use of crude metrics and rankings and encouraging the decision makers to use it responsibly according to [San Fransisco Declaration of Research Assessments (SF-DORA)](https://sfdora.org/read/)
* Encouraging researchers to investigate research questions by conducting meta-research (systematic reviews and meta-analysis) transparently in order to provide better scientific evidences for supporting evidence-based policies


NB: We were inspired by [Munafò, M. R., Nosek, B. A., Bishop, D. V., Button, K. S., Chambers, C. D., Du Sert, N. P., ... & Ioannidis, J. P. (2017). A manifesto for reproducible science. Nature Human Behaviour, 1(1), 0021](https://www.nature.com/articles/s41562-016-0021) when writing our manifesto.


# Our Team

### [Rizqy Amelia Zein](https://rameliaz.github.io/)

Amel is an assistant professor in social psychology, working at Faculty of Psychology, Universitas Airlangga in Surabaya, Indonesia. She is also a [PhD student](https://www.lmu.de/psy/de/personen/kontaktseite/rizqy-amelia-zein-c6eb5d9f.html) at the Chair of Social Psychology, Ludwig-Maximilians-Universität München. Her PhD project focuses on understanding how people relate to scientific and religious explanations. she is broadly interested in doing research in the areas of psychology of religion and psychology of science and also very passionate about research methods, metascience, computational reproducibility, and psychological measurement.

### [Ilham Akhsanu Ridlo](https://orcid.org/0000-0001-5751-3665)

Ilham Akhsanu Ridlo is an assistant professor at the Faculty of Public Health at Universitas Airlangga in Indonesia. He is a Ph.D. candidate at the Institut für Kommunikationswissenschaft und Medienforschung (IfKW) at Ludwig-Maximilians-Universität München. He believes science communication is key to bridging the gap between research practices and health policy implementation. His research focuses on how scientists and journalists influence decision-makers to understand scientific uncertainty. He serves on the advisory board of [The Indonesian Journal of Health Administration (IJHA)](https://e-journal.unair.ac.id/jaki) and is a member of the National Association of Science Writers (NASW). He actively contributes to the media and has founded the [Indonesian Science Communication Labs (IDSCL)](https://idscl.blog/). He writes popular science columns and campaigns for the Open Science movement in Indonesia, especially the Open Access (OA) scientific journal policy. He also participates in the Society of Indonesian Science Journalists (SISJ).

### [Agie Nugroho Soegiono](https://www.researchgate.net/profile/Agie_Soegiono)

Agie is a public policy researcher and currently works as a teaching staff for undergraduate public administration programme at Faculty of Social and Political Sciences, Universitas Airlangga. His research agenda operates within the topics of open governance, smart city, and education for all. Previously, he worked at the Executive Office of the President and contributed to the drafting of Presidential Regulation in regards to open data implementation in Indonesia. His work could be accessed openly and freely through his <a href="https://www.researchgate.net/profile/Agie_Soegiono" target="_blank"><i class="fab fa-researchgate"></i></a> account.


# Spread the word!

Thanks for visiting our website!

Website is maintained by [Rizqy Amelia Zein](https://rameliaz.github.io/) using [`Quarto`](https://quarto.org/docs/websites/) in <a href="https://www.r-project.org" target="_blank"><i class="fab fa-r-project"></i></a>.


# Important to notice

Although this initiative is led and managed by researchers who work at Universitas Airlangga, we **have not been** formally or directly endorsed by the university officials. **Therefore, we do not represent the views/policies of our employer**.