project:
  type: website
  output-dir: docs

website:
  title: "Airlangga Open Science"
  navbar:
    left:
      - text: "🏠"
        href: index.qmd
      - text: "About"
        menu:
          - text: "About (EN)"
            href: en/about.qmd
          - text: "Tentang (ID)"
            href: id/about.qmd
      - text: "Our Events/News (EN)"
        menu:
        - text: "Airlangga #OpenScience is finally here!"
          href: en/wearehere.qmd
        - text: "Planned Activities"
          href: en/plannedactivities.qmd
        - text: "Webinar: Publication Bias"
          href: en/webinarpubbias.qmd
        - text: "Webinar: Advancing Science in Indonesia"
          href: en/webinarscience.qmd
      - text: "Kegiatan Kami (ID)"
        menu:
        - text: "#SainsTerbuka Airlangga Akhirnya Terbentuk!"
          href: id/kamidisini.qmd
        - text: "Rencana Kegiatan"
          href: id/rencanakegiatan.qmd
        - text: "Bias Publikasi dan Preprint"
          href: id/biaspublikasi.qmd
        - text: "Keuntungan Mengadopsi Sains Terbuka"
          href: id/benefit.qmd
        - text: "Petunjuk Mengikuti Webinar"
          href: id/petunjukwebinar.qmd
        - text: "Webinar: Advancing Science in Indonesia"
          href: id/webinarsains.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-expand: true
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">