project:
  type: website
  output-dir: docs

website:
  title: "Airlangga Open Science"
  navbar:
    left:
      - text: "Home - English"
        href: index.qmd
      - text: "Home - Bahasa Indonesia"
        href: id/index.qmd
      - text: "About"
        menu:
          - text: "About (EN)"
            href: about.qmd
          - text: "Tentang (ID)"
            href: id/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">