project:
  type: website
  output-dir: docs

website:
  title: ""
  google-analytics: "G-Q12HZD6EHE"
  navbar:
    left:
      - icon: house
        href: index.qmd
      - text: "About"
        menu:
          - text: "About (EN)"
            href: en/about.qmd
          - text: "Tentang (ID)"
            href: id/about.qmd
      - text: "Our Events/News (EN)"
        menu:
        - text: "Airlangga #OpenScience is finally here!"
          href: en/wearehere.qmd
        - text: "Planned Activities"
          href: en/plannedactivities.qmd
        - text: "Webinar: Publication Bias"
          href: en/webinarpubbias.qmd
        - text: "Webinar: Advancing Science in Indonesia"
          href: en/webinarscience.qmd
      - text: "Kegiatan Kami (ID)"
        menu:
        - text: "#SainsTerbuka Airlangga Akhirnya Terbentuk!"
          href: id/kamidisini.qmd
        - text: "Rencana Kegiatan"
          href: id/rencanakegiatan.qmd
        - text: "Bias Publikasi dan Preprint"
          href: id/biaspublikasi.qmd
        - text: "Keuntungan Mengadopsi Sains Terbuka"
          href: id/benefit.qmd
        - text: "Petunjuk Mengikuti Webinar"
          href: id/petunjukwebinar.qmd
        - text: "Webinar: Advancing Science in Indonesia"
          href: id/webinarsains.qmd
    right:
      - text: "📧"
        href: "mailto:sainsterbuka.ua@gmail.com"
      - icon: github
        href: https://github.com/sainsterbukaUA/sainsterbukaUA
          
  search:
    location: navbar
    type: overlay
  page-footer:
      left: "&#169; 2025 Tim Sains Terbuka Airlangga"
      center: |
        <a class="link-dark me-1" href="https://github.com/sainsterbukaUA" title="github" target="_blank" rel="noopener">{{< iconify fa6-brands github >}}</a>
        <a class="link-dark me-1" href=mailto:sainsterbuka.ua@gmail.com title="Email" target="_blank" rel="noopener">{{< iconify material-symbols:mail >}}</a>
      right: |
        <a class="link-dark me-1" href="https://github.com/sainsterbukaUA/sainsterbukaUA.github.io">{{< iconify fa6-brands github >}} Source</a>

        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    toc-expand: true
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">