project:
  type: website
  output-dir: docs

website:
  title: "Airlangga Open Science"
  navbar:
    left:
      - text: "🏠"
        href: index.qmd
      - text: "Home"
        href: en/index.qmd
      - text: "Laman Utama"
        href: id/index.qmd
      - text: "About"
        menu:
          - text: "About (EN)"
            href: en/about.qmd
          - text: "Tentang (ID)"
            href: id/about.qmd
      - text: "Our Events/News (EN)"
        menu:
        - text: "Airlangga #OpenScience is finally here!"
          href: en/wearehere.qmd
        - text: "Webinar: Publication Bias"
          href: en/webinarpubbias.qmd  
      - text: "Kegiatan Kami (ID)"
        menu:
        - text: "#SainsTerbuka Airlangga Akhirnya Terbentuk!"
          href: id/kamidisini.qmd
        - text: "Bias Publikasi dan Preprint"
          href: id/biaspublikasi.qmd
        - text: "Keuntungan Mengadopsi Sains Terbuka"
          href: id/benefit.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">